### PR TITLE
Fix unsafe use of getAsyncCallback

### LINKED ISSUE #591: getAsyncCallback is not thread-safe
I noticed that `getAsyncCallback` called from Future callbacks.

### PR DESCRIPTION
**Pull request by chbatey**
Fixes #591

### CODE REVIEW

File: core/src/main/scala/akka/persistence/cassandra/query/EventsByPersistenceIdStage.scala [hunk 1]
```diff
@@ -318,20 +331,7 @@ import scala.compat.java8.FutureConverters._
...
-              partition = partitionNr(expectedNextSeqNr)
-              // initial query
-              queryState = QueryIdle
-              query(switchPartition = false)
-
-            case Failure(e) => onFailure(e)
-
-          }.invoke
-        }
+        session.highestDeletedSequenceNumber(persistenceId).onComplete(highestDeletedSequenceNrCb.invoke)
```
Comment (patriknw) [inline core/src/main/scala/akka/persistence/cassandra/query/EventsByPersistenceIdStage.scala]: there is one more in `EventsByPersistenceIdStage.checkForGaps`

Comment (chbatey) [reply core/src/main/scala/akka/persistence/cassandra/query/EventsByPersistenceIdStage.scala]: My grep skills are weak! Doh!
